---
listings-disable-line-numbers: true
code-block-font-size: \scriptsize  

title: Whitepaper
author: Hongjun Ma
date: September 2025
header-includes:
  - \let\oldsection\section
  - \renewcommand{\section}{\clearpage\oldsection}
---
# Optional: define a custom background color
# header-includes:
#   - \usepackage[HTML]{xcolor}
#   - \definecolor{codebg}{HTML}{5F5F5F}

# # All listings options go here:
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=double,rulecolor=\\color{gray!30},backgroundcolor=\\color{codebg}}"
#toc-own-page: true
#code-block-background-color: "333333"          # Dark gray background
#code-block-frame: "double"                      # Double border
#code-block-frame-color: "505050"   

#
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=single,rulecolor=\\color{black},backgroundcolor=\\color{gray!10}}"

#header-includes:
#  - \lstset{breaklines=true,frame=single,rulecolor=\color{black},backgroundcolor=\color[HTML]{F5F5F5}}


#monofont: DejaVuSansMono  
