---
listings: true
listings-disable-line-numbers: true
highlight-style: zenburn

# Optional: define a custom background color
# header-includes:
#   - \usepackage[HTML]{xcolor}
#   - \definecolor{codebg}{HTML}{5F5F5F}

# # All listings options go here:
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=double,rulecolor=\\color{gray!30},backgroundcolor=\\color{codebg}}"
#toc-own-page: true
monofont: "Fira Code"
code-block-font-size: \scriptsize  
code-block-background-color: "333333"          # Dark gray background
code-block-frame: "double"                      # Double border
code-block-frame-color: "505050"   
---
#
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=single,rulecolor=\\color{black},backgroundcolor=\\color{gray!10}}"

#header-includes:
#  - \lstset{breaklines=true,frame=single,rulecolor=\color{black},backgroundcolor=\color[HTML]{F5F5F5}}


#monofont: DejaVuSansMono  
