listings: true
monofont: DejaVuSansMono  # Optional: Specify a monospace font (ensure it’s available in the container)
code-block-font-size: \scriptsize  # Sets code block font size (simpler than \lstset)
header-includes:
  - \lstset{breaklines=true,frame=single,rulecolor=\color{black},backgroundcolor=\color[HTML]{F5F5F5}}
