listings: true
highlight-style: zenburn

# Optional: define a custom background color
# header-includes:
#   - \usepackage[HTML]{xcolor}
#   - \definecolor{codebg}{HTML}{5F5F5F}

# # All listings options go here:
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=single,rulecolor=\\color{black},backgroundcolor=\\color{codebg}}"

code-block-font-size: \scriptsize  
code-block-background-color: "2D2D2D"          # Dark gray background
code-block-frame: "double"                      # Double border
code-block-frame-color: "666666"   

#
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=single,rulecolor=\\color{black},backgroundcolor=\\color{gray!10}}"

#header-includes:
#  - \lstset{breaklines=true,frame=single,rulecolor=\color{black},backgroundcolor=\color[HTML]{F5F5F5}}


#monofont: DejaVuSansMono  
