---
title: HPE on Grafana
author: Hongjun Ma
date: rev1, 2025-09

header-right: "\\rightmark"
footer-left: "rev1, 2025-09"
footer-right: "\\thepage/\\pageref{LastPage}" # current page / total
                    # show date

toc: true
toc-depth: 2
toc-own-page: true

header-includes:
  - \usepackage{lastpage}
  - \makeatletter
  - \renewcommand{\sectionmark}[1]{\markright{##1}}
  - \makeatother

  - \let\oldsection\section
  - \renewcommand{\section}{\clearpage\oldsection}

listings-disable-line-numbers: true
code-block-font-size: \scriptsize  
---

# Optional: define a custom background color
# header-includes:
#   - \usepackage[HTML]{xcolor}
#   - \definecolor{codebg}{HTML}{5F5F5F}

# # All listings options go here:
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=double,rulecolor=\\color{gray!30},backgroundcolor=\\color{codebg}}"
#toc-own-page: true
#code-block-background-color: "333333"          # Dark gray background
#code-block-frame: "double"                      # Double border
#code-block-frame-color: "505050"   

#
#listings-setup: "{basicstyle=\\scriptsize\\ttfamily,breaklines=true,frame=single,rulecolor=\\color{black},backgroundcolor=\\color{gray!10}}"

#header-includes:
#  - \lstset{breaklines=true,frame=single,rulecolor=\color{black},backgroundcolor=\color[HTML]{F5F5F5}}


#monofont: DejaVuSansMono  
