site_name: Grafana 

theme:
  name: material
  palette:
    scheme: slate
nav:
  - Home: whitepaper.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true