site_name: My Docs

theme:
  name: material
  palette:
    scheme: slate
nav:
  - Home: index.md
  - Guide: guide.md
  - Reference: reference.md
  - Cumulus: cumulus.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true