name: Convert Docs

on:
  push:
    paths:
      - 'docs/whitepaper.md'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    # Run the whole job in a container that already has Pandoc + LaTeX
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v4

      - name: Convert to PDF (XeLaTeX handles Unicode)
        run: |
          pandoc docs/whitepaper.md \
            --from=gfm \
            --pdf-engine=xelatex \
            -o docs/whitepaper.pdf

      - name: Convert to Word (DOCX)
        run: |
          pandoc docs/whitepaper.md \
            --from=gfm \
            -o docs/whitepaper.docx

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whitepaper
          path: |
            docs/whitepaper.pdf
            docs/whitepaper.docx
          if-no-files-found: error
          retention-days: 7
