name: Convert Docs

on:
  push:
    paths:
      - 'docs/whitepaper.md'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate PDF with Eisvogel
        uses: docker://pandoc/extra:3.5
        with:
          args: docs/whitepaper.md -o pdf-files/whitepaper.pdf --pdf-engine=xelatex --template=./pandoc/templates/eisvogel.latex

      - name: Commit generated docs back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdf-files/whitepaper.pdf 
          git commit -m "Update generated docs [skip ci]" || echo "No changes to commit"
          git push




      # - name: Convert to PDF (styled, wrapped code)
      #   run: |
      #     pandoc docs/whitepaper.md \
      #       -f gfm+hard_line_breaks+pipe_tables+task_lists+fenced_divs \
      #       --pdf-engine=xelatex \
      #       --template=eisvogel \
      #       --syntax-highlighting=idiomatic \
      #       --resource-path=.:docs \
      #       -H pandoc/code-style.tex \
      #       -V geometry:margin=1in \
      #       -V sansfont="Inter" \
      #       -V monofont="Fira Code" \
      #       -V monofontoptions="Scale=0.85" \
      #       -o docs/whitepaper.pdf


