name: Convert Docs

on:
  push:
    paths:
      - 'docs/whitepaper.md'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install latest Pandoc, TeX & fonts
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            texlive-xetex texlive-latex-recommended texlive-latex-extra \
            fonts-inter fonts-firacode fontconfig curl
          # install latest pandoc (amd64 .deb)
          PVER=$(curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep -Po '"tag_name":\s*"\K[^"]+')
          curl -L -o /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/${PVER}/pandoc-${PVER}-1-amd64.deb
          sudo dpkg -i /tmp/pandoc.deb || sudo apt-get -f install -y
          pandoc --version

      # Eisvogel template (since apt's pandoc doesn't include it)
      - name: Install Eisvogel template
        run: |
          mkdir -p ~/.local/share/pandoc/templates
          curl -fsSL https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/refs/heads/master/template-multi-file/eisvogel.latex \
          -o ~/.local/share/pandoc/templates/eisvogel.latex

      - name: Add header for code wrapping
        run: |
          mkdir -p pandoc
          cat > pandoc/header.tex <<'EOF'
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
          EOF



      - name: Convert to PDF (styled, wrapped code)
        run: |
          pandoc docs/whitepaper.md \
            -f gfm+hard_line_breaks+pipe_tables+task_lists+fenced_divs \
            --pdf-engine=xelatex \
            --template=eisvogel \
            --listings \
            --resource-path=.:docs \
            -H pandoc/code-style.tex \
            -V geometry:margin=1in \
            -V sansfont="Inter" \
            -V monofont="Fira Code" \
            -V monofontoptions="Scale=0.85" \
            -o docs/whitepaper.pdf
      - name: Convert to Word
        run: |
          pandoc docs/whitepaper.md \
            -f gfm+hard_line_breaks+pipe_tables+task_lists+fenced_divs \
            -o docs/whitepaper.docx
      - uses: actions/upload-artifact@v4
        with:
          name: whitepaper
          path: |
            docs/whitepaper.pdf
            docs/whitepaper.docx
