name: Convert Docs

on:
  push:
    paths:
      - 'docs/whitepaper.md'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/extra:3

    steps:
      - uses: actions/checkout@v4
      - name: Add header for code wrapping
        run: |
          mkdir -p pandoc
          cat > pandoc/header.tex <<'EOF'
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
          EOF
      - name: Convert to PDF (styled, wrapped code)
        run: |
          pandoc docs/whitepaper.md \
            -f gfm+hard_line_breaks+pipe_tables+task_lists+fenced_divs \
            --pdf-engine=xelatex \
            --template=eisvogel \
            --listings \
            --resource-path=.:docs \
            -H pandoc/code-style.tex \
            -V geometry:margin=1in \
            -V sansfont="Noto Sans" \
            -V monofont="Liberation Mono" \
            -o docs/whitepaper.pdf
      - name: Convert to Word
        run: |
          pandoc docs/whitepaper.md \
            -f gfm+hard_line_breaks+pipe_tables+task_lists+fenced_divs \
            -o docs/whitepaper.docx
      - uses: actions/upload-artifact@v4
        with:
          name: whitepaper
          path: |
            docs/whitepaper.pdf
            docs/whitepaper.docx
